### ISSUE TITLE
Dext.Tool.exe scaffolding generates broken unit

### ISSUE THREAD

**Issue by mtsre** [cesarliws/dext#101]
Hello there, I am trying to generate entity classes and faced several roadblocks.

Im using Delphi 13 (64-Bit) with dext 25d9252

I tried DextTool.exe from Apps/CLI/DextTool.dpr since it is part of group project for building dext.

To get scaffolding to work for a firebase database, I had to change how the connection string is passed in Apps/CLI/Commands/Dext.Hosting.CLI.Commands.Scaffold.pas:
```pascal
//FDConnection.Params.Text := ConnectionStr; // before
FDConnection.ConnectionString := ConnectionStr;
```
After that I got it to generate entities but they are broken:
- missing F prefix for variables
- missing include for TPropExpression
- `[PK] property Id` is case sensitive and will fail with "unknown column Id" at runtime without adding `[Column('ID')]`

The [book](https://github.com/cesarliws/dext/blob/main/Docs/Book/09-cli/scaffolding.md) says there is `--template` parameter and that it should use a default template, but in the code, only Tools/Dext.CLI/Dext.CLI.App.pas actually uses templates. Sadly I am not able to build that project (Tools/Dext.CLI/dext.dpr) since I get an error which I was not able to fix:
`Dext.Entity.Mapping.pas(44): F2051 Unit Dext.Core.SmartTypes was compiled with a different version of Dext.Types.Nullable.Nullable`1.&op_Implicit`

The [documentation](https://github.com/cesarliws/dext/blob/main/Docs/Book/09-cli/README.md) does not make it clear how to use the CLI in that regard. The Quick Reference shows commands like `dext scaffold ...` but the group project does not build dext.exe it builds DextTool.exe. After the Quick Refrence the documentations has an installation part which says to add the CLI to my own project but when I tried that there was no scaffold command to use.

**Comment by cesarliws** [comment]
Hello @mtsre, thank you very much for your detailed feedback! 

We have addressed all the roadblocks you mentioned and introduced several enhancements to make the CLI more robust:

### 🛠️ Fixes & Enhancements:
1.  **Connection Strings**: Fixed the assignment in the Scaffold command. It now correctly uses `FDConnection.ConnectionString`, supporting complex connection strings (including Firebase/Firestore via FireDAC).
2.  **Field Naming**: Fixed the missing `F` prefix for generated private fields.
3.  **Metadata & Units**: Fixed the missing `TPropExpression` unit references. Metadata generation is now more granular and can be toggled via flags.
4.  **Case Sensitivity**: The engine now automatically detects if a property name differs from the database column name (including case sensitivity) and explicitly generates the `[Column('REAL_NAME')]` attribute, ensuring runtime stability.
5.  **Reserved Keywords**: We implemented automatic identifier escaping. If your database contains columns named after Delphi reserved words (e.g., `Class`, `Begin`, `End`), the CLI will now correctly generate them as `&Class`, `&Begin`, etc.
6.  **Binary Naming**: We clarified that `DextTool.dproj` is the source for the `.\Apps\dext.exe` binary. We've also added a compiler **HINT** directly in the `.dpr` to inform developers where the binary is generated.

### 🚀 New Generation Modes:
We've introduced two property styles to suit different architectural needs:
-   **Smart Properties (Default)**: Uses Dext's high-performance `SmartTypes` (`IntType`, `StringType`, etc.) for zero-allocation and built-in lazy loading.
-   **POCO Mode (`--poco`)**: Generates traditional entities using native Delphi types (`Integer`, `string`) and `Nullable<T>`.

### 🔍 Troubleshooting the Compilation Error:
The error `F2051 Unit ... was compiled with a different version` is typically caused by stale `.dcu` files or duplicate units in your Delphi Library Path. We've added a new **Troubleshooting** section to the documentation with a step-by-step guide to perform a clean build and resolve these environment issues.

You can check the updated and more didactic documentation here: 
- [Scaffolding Guide (EN)](https://github.com/dext-framework/dext/blob/master/Docs/Book/09-cli/scaffolding.md)
- [Guia de Scaffolding (PT-BR)](https://github.com/dext-framework/dext/blob/master/Docs/Book.pt-br/09-cli/scaffolding.md)

Thank you again for helping us make Dext an industrial-grade framework!

**Comment by mtsre** [comment]
Thanks for the quick fix @cesarliws 

I get an error with the latest version running the scaffold command:
```
Error: Failed to connect: [FireDAC][Phys]-300. Driver [FB] is not registered. To register it, you can drop component [TFDPhysFBDriverLink] into your project
```
Had to include `FireDAC.Phys.FB` in `dext\Apps\CLI\Commands\Dext.Hosting.CLI.Commands.Scaffold.pas`
to get around it.

After that it runs fine and the generated unit works right away.

I get new errors now for dates / timestamps which must have been introduced after 25d9252:
Calling `DbSet.ToList` results in multiple of the following exception:
```
First chance exception at $00007FFB94DFCF19. Exception class EDateTimeException with message 'Invalid date string: 26.03.2026 16:50:04'. Process DextHelloWorld.exe (6360)
```
After that I get this exception for calling `C.ChangedAt.AsDateTime`:
```
First chance exception at $00007FFB94DFCF19. Exception class EDateTimeException with message 'Invalid date string: 00:00:00'. Process DextHelloWorld.exe (6360)
```
This is with windows regional format set to German (short date: dd.mm.yyyy).

**Comment by cesarliws** [comment]
Hi @mtsre! 

Thank you for the detailed feedback and for helping us track down these edge cases. Both issues have been addressed in the latest commit:

1.  **FireDAC Driver Registration**: Fixed. The missing driver links were added to the CLI tool. The `Dext.Entity.Drivers.FireDAC.Links` unit is now properly included, ensuring that Firebird (FB) and other common drivers are automatically registered.
2.  **Date/Timestamp Globalization**: This was a great catch. We've overhauled the date parsing logic in `Dext.Core.DateUtils` to be "locale-aware" while maintaining JSON standards.
    *   **Invariant for JSON**: We now strictly enforce `TFormatSettings.Invariant` during JSON serialization/deserialization to ensure that numbers and dates are consistent across different environments.
    *   **Locale Fallback**: For parsing dates like your German format (`dd.mm.yyyy`), the `TryParseCommonDate` utility now uses the system's regional settings as a primary fallback before trying ISO and common delimiters.
    *   **DataSet Hydration**: Improved `TEntityDataSet` to handle ISO8601 strings more robustly during hydration, including specific logic for `TDate`, `TTime`, and `TDateTime` properties.

We've also added a new chapter to the **Dext Book** (under *Advanced Topics > Serialization & Globalization*) explaining these changes in detail.

Please pull the latest version and let us know if it works as expected in your German locale!

**Comment by mtsre** [comment]
Thanks again for the quick fix @cesarliws 

I am happy to report that the timestamp in my german locale is working now as expected without getting exceptions.

This time I also remembered to enable the drivers again in dext.inc after git restore and pull, so the error with the missing FB driver was probably on me, my bad.

**Comment by mtsre** [comment]
I just noticed that scaffolding does not find and generate code for foreign keys any longer. 
I tried different parameter combinations of `--fluent`, `--poco`, `--smart`, `--with-metadata` and `--table` but foreign keys are always just handled like normal columns.
This regression must have been introduced in recent commits since I still got older generated unit files that have the code for foreign keys.

**Comment by cesarliws** [comment]
@mtsre It's generating for SQLite, since I tested it yesterday, I'll run the tests with Firebird as well and commit the fixes as soon as I finish testing.

**Comment by cesarliws** [comment]
Hi @mtsre,

I've just pushed a series of fixes that stabilize the Firebird scaffolding and restore the foreign key generation.

The regression was caused by a combination of inconsistent metadata extraction across different database drivers and a case-sensitivity mismatch in our internal metadata cache. Here is a summary of the improvements:

*   **Robust Foreign Key Discovery:** We implemented a high-performance custom metadata extraction for Firebird that bypasses some limitations in standard FireDAC metadata. It now correctly identifies relationships even in complex scenarios.
*   **Resolved "Ghost" Properties:** Fixed a bug where the engine was generating invalid properties with empty names (e.g., `property : Lazy<T>`) when metadata was incomplete. These are now properly validated and skipped.
*   **Resilient Naming Logic:** The identifier cleaning logic is now more resilient, ensuring that navigation properties always result in valid Delphi identifiers.
*   **Correct Type Mapping:** Fixed the mapping for Firebird `TIMESTAMP` fields, which will now correctly generate `TDateTime` (or `DateTimeType`) instead of `TTime`.
*   **Case-Insensitive Cache:** The metadata engine now handles table and constraint names case-insensitively, which is critical for Firebird's system tables.

I've validated the generation against the standard `EMPLOYEE.FDB` and confirmed that all foreign keys are being mapped correctly now.

Please pull the latest changes, rebuild your `DextTool` CLI (or the package), and run the scaffold command again. Let me know if everything is working as expected on your end!

**Comment by mtsre** [comment]
Hello @cesarliws,
unfortunately I got to report more problems.

The generated code now adds 2 properties for every foreign key:
```pascal
    [Column('USER_ID')]
    property UserId: IntType read FUserId write FUserId;
...
    [ForeignKey('USER_ID')]
    property User: Lazy<TUser> read FNavUser write FNavUser;
    [ForeignKey('USER_ID')]
    property User2: Lazy<TUser> read FNavUser2 write FNavUser2;   
```
My simple query: `DbSet.Where(cr.Id < 10).ToList;` now fails because these properties get added to the select statement: 
```SQL
 SELECT "ID", "USER_ID", "CONTACT_ID",  "User", "Contact", "User2", "Contact2" FROM "CONTACTS_REL" WHERE ("ID" < :p1)
```
Since you said you tested with a Firebase database, I assume you did not run into these problems, so my guess is the cause might be the version of the database involved.

Anyways, I will stop reporting back for now, and might check out the project again later when it is more mature. Good luck.

**Comment by cesarliws** [comment]
Hello @mtsre,

First of all, I would like to sincerely apologize for these issues. Your feedback has been incredibly valuable, and it's exactly this kind of real-world stress test that helps Dext mature. I completely understand the frustration of running into blockers, but I would like to ask you to please keep reporting any issues you find. Your contributions are making the framework much more robust.

I have identified and fixed the two root causes you reported:

1.  **SQL Select Leakage**: You were absolutely right. The `TSQLGenerator` was incorrectly including navigation properties (`Lazy<T>`) in the default `SELECT` statement. This has been hardened, and now all navigation properties and class/interface types are strictly filtered out from the generated SQL.
2.  **Property Duplication (`User2`)**: This was caused by redundant metadata returned by some database drivers/versions during foreign key extraction. I've implemented a deduplication logic in the `TFireDACSchemaProvider` that merges these entries before the code generation starts, preventing the creation of redundant properties.

These fixes are being merged now. If you're willing to give it another try, I'd love to hear if this resolves the issues in your environment.

Thank you again for your patience and for helping us make Dext better.

Best regards,
Cesar Romero

**Comment by cesarliws** [comment]
Hello @mtsre,

Following up on my previous message, I wanted to let you know that I've performed a much deeper dive into Firebird support to ensure we've caught these and other potential edge cases. I realized that our previous tests were a bit too superficial for complex schemas.

I have now set up a dedicated verification environment where I scaffold the entire standard **EMPLOYEE.FDB** sample database and run a full hydration test across all tables. During this process, I discovered and fixed another critical issue: **Firebird ARRAY columns** (like `VARCHAR[1:5]` or `INTEGER[1:4]`) were causing arithmetic and variant conversion errors during hydration. These are now correctly detected and handled (excluded from scalar projections) by the scaffolding engine.

Combined with the fixes for property duplication and SQL leakage mentioned before, the framework is now significantly more stable and has been verified against all tables in the Firebird sample database.

If you are willing to give it another try, I would really appreciate it. If you encounter any other unsupported database resources or specific behaviors in your environment, please let me know so we can implement the necessary support.

Thank you again for helping us harden the Dext Framework!

Best regards,
Cesar Romero"
